### ISSUE TITLE
Not working with latest chart.js 2

### ISSUE THREAD

**Issue by maxtuzz** [evoila/angular2-chartjs2#1]
Was trying to get this working with latest Charts V2. But whenever I try and render a simple bar chart I'm getting the following error: 

```
angular2.dev.js:25644 TypeError: Cannot read property 'clientHeight' of undefined
    at BaseChart.refresh (ChartRenderer.ts:217)
    at BaseChart.Object.defineProperty.set [as data] (ChartRenderer.ts:143)
    at AppView._View_PostsComponent1.detectChangesInternal (PostsComponent.template.js:120)
    at AppView.detectChanges (angular2.dev.js:23638)
    at AppView.detectContentChildrenChanges (angular2.dev.js:23657)
    at AppView._View_PostsComponent0.detectChangesInternal (PostsComponent.template.js:64)
    at AppView.detectChanges (angular2.dev.js:23638)
    at AppView.detectViewChildrenChanges (angular2.dev.js:23662)
    at AppView._View_PostsComponent_Host0.detectChangesInternal (PostsComponent_Host.template.js:30)
    at AppView.detectChanges (angular2.dev.js:23638)
```

**Comment by jhiemer** [comment]
@maxtuzz let me check that. Which version of Chart.js V2 are you using?

**Comment by jhiemer** [comment]
@maxtuzz tested just right away with 2.1.0 an it works without any problems. Could you provide more code?

**Comment by maxtuzz** [comment]
Sure. It's just a test. I've got 2.0.2 at the moment, but i'll try with 2.1.0. 

I am using Angular 2 beta 17, but have also tried on betas 15, and 16.

posts.component.html
```
import {ChartRenderer} from "./ChartRenderer";

@Component({
    selector: 'posts',
    templateUrl: '/app/posts/posts.component.html',
    directives: [ChartRenderer]
})
export class PostsComponent implements OnInit {
    charts = [];
    data = [];

    ngOnInit() {
        var firstChart = {
            data: [
            [65, 59, 80, 81, 56, 55, 40],
            [28, 48, 40, 19, 86, 27, 90],
            [18, 48, 77, 9, 100, 27, 40]
            ],
            labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
            series: ['Series A', 'Series B', 'Series C'],
            options: {
                responsive: true,
                multiTooltipTemplate: '<%if (datasetLabel){%><%=datasetLabel %>: <%}%><%= value %>'
            }
        };

        this.charts.push(firstChart);
    }
}
```
posts.component.html
```
<div *ngFor="let chart of charts" style="width:100%;height:100%;">
    <base-chart class="chart"
                [data]="chart.data"
                [labels]="chart.label"
                [options]="chart.options"
                [series]="chart.series"
                [chartType]="chart.type"></base-chart>
</div>
```

Thanks for your help,
Max

**Comment by maxtuzz** [comment]
If possible. Could you provide a demo implementation using latest Charts 2.1.0 on plnkr or something?

Very possibly something on my end. 

Cheers,
Max

**Comment by jhiemer** [comment]
You do not provider chart.type in:

```javascript
var firstChart = {
            data: [
            [65, 59, 80, 81, 56, 55, 40],
            [28, 48, 40, 19, 86, 27, 90],
            [18, 48, 77, 9, 100, 27, 40]
            ],
            labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
            series: ['Series A', 'Series B', 'Series C'],
            options: {
                responsive: true,
                multiTooltipTemplate: '<%if (datasetLabel){%><%=datasetLabel %>: <%}%><%= value %>'
            }
        };
````
do you?

**Comment by maxtuzz** [comment]
Gah sorry, that is in there. I just screwed up the formatting here as I filled those lasts lines manually. 

```
var firstChart = {
            data: [
            [65, 59, 80, 81, 56, 55, 40],
            [28, 48, 40, 19, 86, 27, 90],
            [18, 48, 77, 9, 100, 27, 40]
            ],
            labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
            series: ['Series A', 'Series B', 'Series C'],
            options: {
                responsive: true,
                multiTooltipTemplate: '<%if (datasetLabel){%><%=datasetLabel %>: <%}%><%= value %>'
            },
            type: "bar" <------ here
        };
```

But yeah same error persists.

**Comment by jhiemer** [comment]
@maxtuzz could you please show me ChartRenderer.ts:217 of your file? In my file it is:

````
let hasData = this.data && this.data.length > 0;
````
Which has no `clientHeight` property call at all?

**Comment by maxtuzz** [comment]
Ok so that would be the reason. Turns out this specific error was my issue. 

I had the following code there and had left it long enough to not realize it wasn't yours: 
```
        if (this.options.responsive && this.parent.clientHeight === 0) {
            return setTimeout(() => this.refresh(), 50);
        }
```

So now I just get nothing rendering. But no errors. My Chart array is being populated correctly though, just nothing is rendering.

With the following template:
```
<h1>Charts</h1>
<div *ngFor="let chart of charts" style="width:100%;height:100%;">
    <base-chart class="chart"
                [data]="chart.data"
                [labels]="chart.label"
                [options]="chart.options"
                [series]="chart.series"
                [chartType]="chart.type"></base-chart>
</div>
<h2>Test</h2>
```
This is what is rendered: 
![screenshot from 2016-05-04 19-07-28](https://cloud.githubusercontent.com/assets/6403172/15007253/7bfbfb58-122b-11e6-98e0-ba6d6d7605ea.png)

**Comment by jhiemer** [comment]
Are you using bootstrap? Canvas element is added to the DOM?

**Comment by maxtuzz** [comment]
Yeah I'm using bootstrap for this test. The canvas element is being correctly added to the dom. 

Also fixed other elements not being rendered:
![screenshot from 2016-05-04 19-26-32](https://cloud.githubusercontent.com/assets/6403172/15007574/380c0714-122e-11e6-9f98-faa2ed06af04.png)

**Comment by maxtuzz** [comment]
Just confirmed same issue of it not being rendered without bootstrap styles (was only using the css).

**Comment by maxtuzz** [comment]
Just replicated the issue in Ionic with no bootstrap or traditional routing.

**Comment by jhiemer** [comment]
Try to add the following css:

```css
.chart {
  display: block;
  width: 100%;
}

ul[class^='chart-'] {
  list-style-type: none;
  margin-top: 5px;
  text-align: center;
  -webkit-padding-start: 0;
  -moz-padding-start: 0;
  padding-left: 0
}

ul[class^='chart-'] li {
  display: inline-block;
  white-space: nowrap;
  position: relative;
  padding: 5px 25px 25px 5px;
  font-size: smalsler;
}

ul[class^='chart-'] li span {
  border-radius: 5px;
  padding: 4px;
}
````

**Comment by maxtuzz** [comment]
Unfortunately this has no effect.

**Comment by jhiemer** [comment]
Then I have no idea. Charts are rendered correctly on my side.

![screen shot 2016-05-04 at 10 22 47](https://cloud.githubusercontent.com/assets/1557826/15008666/2f26529a-11e2-11e6-95c3-6693e57024e7.png)

**Comment by jhiemer** [comment]
You can create a plunkr, the I can take a look at it.

**Comment by maxtuzz** [comment]
Sure. I'll do that. In the mean time if that's a demo project would you mind uploading it as an example so I can debug the differences?

**Comment by jhiemer** [comment]
@maxtuzz created a plunker?

**Comment by maxtuzz** [comment]
Yeah: [Plunker](https://plnkr.co/edit/kLcvQ3jPJzgjskhRraQ7?p=preview)
As you can see when you spam the 'Add chart' button, the dom will expand but nothing is rendered.

**Comment by jhiemer** [comment]
Looking at your plunkr I see two mistakes:
* you are missing the type definition
* you define chart.label, but you referencing chart.labels
* you need to include moment.js

then the chart should work.

**Comment by maxtuzz** [comment]
Thanks for the catch on label. But these other dependencies should really be mentioned in the instructions. 

Consider this closed for now.
